theme: jekyll-theme-minimal
title: Design Space Exploration and Explanation via CVAEs in Pedestrian Bridges
description: This is the accompanying GitHub to the paper "Design Space Exploration and Explanation via Conditional Variational Autoencoders in Meta-model-based Conceptual Design of Pedestrian Bridges" that can be found on !https://arxiv.org/abs/2211.16406
